package entities;
// Generated Oct 10, 2012 2:24:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Assignment generated by hbm2java
 */
public class Assignment  implements java.io.Serializable {


     private int assignmentId;
     private Classes classes;
     private Staff staff;
     private Subject subject;
     private String name;
     private String url;
     private Set<Mark> marks = new HashSet<Mark>(0);

    public Assignment() {
    }

	
    public Assignment(int assignmentId, String name, String url) {
        this.assignmentId = assignmentId;
        this.name = name;
        this.url = url;
    }
    public Assignment(int assignmentId, Classes classes, Staff staff, Subject subject, String name, String url, Set<Mark> marks) {
       this.assignmentId = assignmentId;
       this.classes = classes;
       this.staff = staff;
       this.subject = subject;
       this.name = name;
       this.url = url;
       this.marks = marks;
    }
   
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set<Mark> getMarks() {
        return this.marks;
    }
    
    public void setMarks(Set<Mark> marks) {
        this.marks = marks;
    }




}


