package entities;
// Generated Oct 10, 2012 2:24:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int studentId;
     private Classes classes;
     private String username;
     private String password;
     private String fullname;
     private int sort;
     private int enable;
     private Set<Mark> marks = new HashSet<Mark>(0);

    public Student() {
    }

	
    public Student(int studentId, String username, String password, String fullname, int sort, int enable) {
        this.studentId = studentId;
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.sort = sort;
        this.enable = enable;
    }
    public Student(int studentId, Classes classes, String username, String password, String fullname, int sort, int enable, Set<Mark> marks) {
       this.studentId = studentId;
       this.classes = classes;
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.sort = sort;
       this.enable = enable;
       this.marks = marks;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public int getSort() {
        return this.sort;
    }
    
    public void setSort(int sort) {
        this.sort = sort;
    }
    public int getEnable() {
        return this.enable;
    }
    
    public void setEnable(int enable) {
        this.enable = enable;
    }
    public Set<Mark> getMarks() {
        return this.marks;
    }
    
    public void setMarks(Set<Mark> marks) {
        this.marks = marks;
    }




}


