package entities;
// Generated Oct 10, 2012 2:24:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Mark generated by hbm2java
 */
public class Mark  implements java.io.Serializable {


     private MarkId id;
     private Assignment assignment;
     private Student student;
     private Double mark;

    public Mark() {
    }

	
    public Mark(MarkId id, Assignment assignment, Student student) {
        this.id = id;
        this.assignment = assignment;
        this.student = student;
    }
    public Mark(MarkId id, Assignment assignment, Student student, Double mark) {
       this.id = id;
       this.assignment = assignment;
       this.student = student;
       this.mark = mark;
    }
   
    public MarkId getId() {
        return this.id;
    }
    
    public void setId(MarkId id) {
        this.id = id;
    }
    public Assignment getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Double getMark() {
        return this.mark;
    }
    
    public void setMark(Double mark) {
        this.mark = mark;
    }




}


