package entities;
// Generated Oct 10, 2012 2:24:08 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private int subjectId;
     private String name;
     private int sort;
     private int enable;
     private Set<Assignment> assignments = new HashSet<Assignment>(0);

    public Subject() {
    }

	
    public Subject(int subjectId, String name, int sort, int enable) {
        this.subjectId = subjectId;
        this.name = name;
        this.sort = sort;
        this.enable = enable;
    }
    public Subject(int subjectId, String name, int sort, int enable, Set<Assignment> assignments) {
       this.subjectId = subjectId;
       this.name = name;
       this.sort = sort;
       this.enable = enable;
       this.assignments = assignments;
    }
   
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getSort() {
        return this.sort;
    }
    
    public void setSort(int sort) {
        this.sort = sort;
    }
    public int getEnable() {
        return this.enable;
    }
    
    public void setEnable(int enable) {
        this.enable = enable;
    }
    public Set<Assignment> getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set<Assignment> assignments) {
        this.assignments = assignments;
    }




}


